version: "3.7"

services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      - HOST_GID
      - HOST_UID
      - FB_PROFILE
      - MASTODON_ACCESS_TOKEN
      - MASTODON_ACCOUNT
    volumes:
      - tmp-data:/opt/mastodon_facebook_cover_image/tmp

volumes:
  tmp-data:
